# Generated by Django 2.1.7 on 2019-03-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_administration_custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='permission',
            field=models.CharField(blank=True, choices=[('test', 'test'), ('real', 'real')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='db',
            name='test',
            field=models.CharField(max_length=15),
        ),
    ]
